#!/usr/bin/env bash

APP_NAME=$1
APP_PATH=$2
APP_SOURCE_URL=$3
APP_SOURCE_REVISION=$4

pm2 delete ${APP_NAME}

cd ${APP_PATH}
source .bootstrap

rm -rf current || true

git clone ${APP_SOURCE_URL} current
cd current
git checkout ${APP_SOURCE_REVISION}

npm install --production

pm2 start index.js -i max --name ${APP_NAME}

# pm2 save