#!/usr/bin/env bash

APP_NAME=$1
APP_PATH=$2
APP_SOURCE_URL=$3
APP_SOURCE_REVISION=$4

pm2 delete ${APP_NAME}

# loading releases
npm install async@2.0.0-rc.6
npm install mongoose@4.5.9

RELEASES=`node release-find`
if [ $? -ne 0 ]; then
   echo "error finding releases: ${RELEASES}" 1>&2
   exit 1
fi

cd ${APP_PATH}
echo "================ updating releases ================" >> .other
echo -e ${RELEASES} >> .bootstrap
echo -e ${RELEASES} >> .other
echo ${RELEASES}
source .bootstrap

rm -rf current || true

git clone ${APP_SOURCE_URL} current
cd current
git checkout ${APP_SOURCE_REVISION}

npm install --production

pm2 start server.js -i max --name ${APP_NAME}

# pm2 save