#!/usr/bin/env bash

APP_NAME=$1
APP_PATH=$2
APP_SOURCE_URL=$3
APP_SOURCE_REVISION=$4

pm2 delete ${APP_NAME}

# loading releases
RELEASES=`node release-find`
if [ $? -ne 0 ]; then
   echo "error finding releases: ${RELEASES}" 1>&2
   exit 1
fi
cat ${RELEASES} >> .bootstrap

cd ${APP_PATH}
source .bootstrap

rm -rf current || true

git clone ${APP_SOURCE_URL} current
cd current
git checkout ${APP_SOURCE_REVISION}

npm install --production

pm2 start server.js -i max --name ${APP_NAME}

# pm2 save