#!/usr/bin/env bash

APP_NAME=$1
APP_PATH=$2
APP_SOURCE_URL=$3
APP_SOURCE_REVISION=$4
APP_SOURCE_REVISION=${APP_SOURCE_REVISION:=master}

CURRENT=`pwd`

cd ${APP_PATH}
source .bootstrap

git clone ${APP_SOURCE_URL} current
cd current
git checkout ${APP_SOURCE_REVISION}

RELEASE=${APP_SOURCE_REVISION} # `git rev-parse HEAD`
PREFIX="$APP_NAME/$RELEASE"

component build --out serand --name serand --copy --prefix ${PREFIX}

cd ${CURRENT}

npm install aws-sdk@2.4.5
npm install async@2.0.0-rc.6
npm install node-uuid@1.4.7

node components-uploader "$APP_PATH/current/$APP_NAME" ${PREFIX}

# pm2 save