#!/usr/bin/env bash

echo "starting"

APP_NAME=$1
APP_PATH=$2
APP_SOURCE_URL=$3
APP_SOURCE_REVISION=$4
APP_SOURCE_REVISION=${APP_SOURCE_REVISION:=master}

echo ${APP_NAME}
echo ${APP_PATH}
echo ${APP_SOURCE_URL}
echo ${APP_SOURCE_REVISION}

CURRENT=`pwd`

echo ${CURRENT}

cd ${APP_PATH}
source .bootstrap

rm -rf current || true

git clone ${APP_SOURCE_URL} current
cd current
git checkout ${APP_SOURCE_REVISION}

VERSION=${APP_SOURCE_REVISION} # `git rev-parse HEAD`
VERSION=`date +%s`
LOCATION=${APP_NAME}/${VERSION}
PREFIX=/${LOCATION}/

component build --out ${APP_NAME} --name index --prefix ${PREFIX}

cd ${CURRENT}

npm install aws-sdk@2.4.5
npm install async@2.6.0
npm install node-uuid@1.4.7
npm install mime-types@2.1.11
npm install mongoose@5.*

node components-uploader "$APP_PATH/current/$APP_NAME" ${LOCATION}
node release-create ${APP_NAME} ${VERSION} ${APP_SOURCE_REVISION}

# pm2 save