#!/usr/bin/env bash

APP_PATH=$1
APP_SOURCE_URL=$2
APP_SOURCE_REVISION=$3

pkill node

mkdir $APP_PATH
cd $APP_PATH

git clone $APP_SOURCE_URL .
git checkout $APP_SOURCE_REVISION

npm install --production

source .bootstrap
nohup node server.js > nohup.out &