#!/usr/bin/env node
var mongoose = require('mongoose');
var models = require('./models');

var name = process.argv[2];
var version = process.argv[3];
var revision = process.argv[4];

var certPath = process.env.CERT_SERANDIVES;
var pemPath = process.env.PEM_SERVER;
var mongourl = process.env.MONGODB_URI;

var ca = certPath ? fs.readFileSync(certPath) : null;
var pem = pemPath ? fs.readFileSync(pemPath) : null;

mongoose.connect(mongourl, {
    useMongoClient: true,
    authSource: 'admin',
    ssl: !!pem,
    sslCA: ca,
    sslCert: pem,
    sslKey: pem
});

models.Release.create({
    type: 'serandomps',
    name: name,
    version: version,
    revision: revision
}, function (err) {
    if (err) {
        console.error(err);
        return process.exit(1);
    }
    process.exit(0);
});