name 'mongodb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mongodb'
long_description 'Installs/Configures mongodb'
version '0.1.0'
