#!/usr/bin/env node

var fs = require('fs');
var AWS = require('aws-sdk');

var awsKey = process.argv[2]
var awsSecret = process.argv[3]
var bucket = process.argv[4]
var from = process.argv[5]
var to = process.argv[6]

var config = new AWS.Config({
    accessKeyId: awsKey,
    secretAccessKey: awsSecret
});

var s3 = new AWS.S3(config);

s3.getObject({
    Bucket: bucket,
    Key: from
}, function (err, data) {
    if (err) {
        console.error(err);
        return process.exit(1);
    }
    fs.writeFile(to, data.Body, function (err) {
        if (err) {
            console.error(err);
            return process.exit(1);
        }
        process.exit(0);
    });
});
