#!/usr/bin/env bash

apt-get install -y g++

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get install -y mongodb

# ln -s `which mongodb` /usr/bin/node

node --version
npm --version