#!/usr/bin/env bash

AWS_KEY=$1
AWS_SECRET=$2
MONGODB_USERNAME_ADMIN=$3
MONGODB_PASSWORD_ADMIN=$4

./install "${AWS_KEY}" "${AWS_SECRET}" "${MONGODB_USERNAME_ADMIN}" "${MONGODB_PASSWORD_ADMIN}"

mv /etc/mongod-custom.conf /etc/mongod.conf

service mongod start

sleep 2

mongo --version